# Generated by Django 5.0.3 on 2024-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingr',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
