# Generated by Django 5.0.3 on 2024-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_ingr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingr',
            field=models.CharField(default='', max_length=20),
        ),
    ]
